server:
  port: 8002
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  application:
    name: demo-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config