server:
  port: 8001

spring:
  application:
    name: zm-eureka
  security:
    user:
      name: zm
      password: zm123

eureka:
  datacenter: cloud
  environment: product
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}(${spring.cloud.client.ipAddress}):${server.port}
    metadata-map:
      instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://zm:zm123@127.0.0.1:${server.port}/eureka/